[[pages]]
path = "pages/dashboard_page.py"
name = "Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "pages/segmentation_page.py"
name = "Segmentation"
icon = "ğŸ§©"

[[pages]]
path = "pages/ltv_page.py"
name = "Lifetime Value"
icon = "ğŸ’°"

[[pages]]
path = "pages/churn_page.py"
name = "Churn"
icon = "ğŸ“‰"